//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Entities
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DataBase : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DataBase”部分中的连接字符串初始化新 DataBase 对象。
        /// </summary>
        public DataBase() : base("name=DataBase", "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DataBase 对象。
        /// </summary>
        public DataBase(string connectionString) : base(connectionString, "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DataBase 对象。
        /// </summary>
        public DataBase(EntityConnection connection) : base(connection, "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ActivityRow> tblActivity
        {
            get
            {
                if ((_tblActivity == null))
                {
                    _tblActivity = base.CreateObjectSet<ActivityRow>("tblActivity");
                }
                return _tblActivity;
            }
        }
        private ObjectSet<ActivityRow> _tblActivity;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerRow> tblCustomer
        {
            get
            {
                if ((_tblCustomer == null))
                {
                    _tblCustomer = base.CreateObjectSet<CustomerRow>("tblCustomer");
                }
                return _tblCustomer;
            }
        }
        private ObjectSet<CustomerRow> _tblCustomer;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<InviteRow> tblInvite
        {
            get
            {
                if ((_tblInvite == null))
                {
                    _tblInvite = base.CreateObjectSet<InviteRow>("tblInvite");
                }
                return _tblInvite;
            }
        }
        private ObjectSet<InviteRow> _tblInvite;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CountRow> tblCount
        {
            get
            {
                if ((_tblCount == null))
                {
                    _tblCount = base.CreateObjectSet<CountRow>("tblCount");
                }
                return _tblCount;
            }
        }
        private ObjectSet<CountRow> _tblCount;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tblActivity EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblActivity(ActivityRow activityRow)
        {
            base.AddObject("tblActivity", activityRow);
        }
    
        /// <summary>
        /// 用于向 tblCustomer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblCustomer(CustomerRow customerRow)
        {
            base.AddObject("tblCustomer", customerRow);
        }
    
        /// <summary>
        /// 用于向 tblInvite EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblInvite(InviteRow inviteRow)
        {
            base.AddObject("tblInvite", inviteRow);
        }
    
        /// <summary>
        /// 用于向 tblCount EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotblCount(CountRow countRow)
        {
            base.AddObject("tblCount", countRow);
        }

        #endregion

        #region 函数导入
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public int ProCount()
        {
            return base.ExecuteFunction("ProCount");
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="ActivityRow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivityRow : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ActivityRow 对象。
        /// </summary>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        public static ActivityRow CreateActivityRow(global::System.Int64 activityID)
        {
            ActivityRow activityRow = new ActivityRow();
            activityRow.ActivityID = activityID;
            return activityRow;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int64 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int64 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActivityTime
        {
            get
            {
                return _ActivityTime;
            }
            set
            {
                OnActivityTimeChanging(value);
                ReportPropertyChanging("ActivityTime");
                _ActivityTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivityTime");
                OnActivityTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActivityTime;
        partial void OnActivityTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnActivityTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IndustryDes
        {
            get
            {
                return _IndustryDes;
            }
            set
            {
                OnIndustryDesChanging(value);
                ReportPropertyChanging("IndustryDes");
                _IndustryDes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IndustryDes");
                OnIndustryDesChanged();
            }
        }
        private global::System.String _IndustryDes;
        partial void OnIndustryDesChanging(global::System.String value);
        partial void OnIndustryDesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AttendTotal
        {
            get
            {
                return _AttendTotal;
            }
            set
            {
                OnAttendTotalChanging(value);
                ReportPropertyChanging("AttendTotal");
                _AttendTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttendTotal");
                OnAttendTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _AttendTotal;
        partial void OnAttendTotalChanging(Nullable<global::System.Int32> value);
        partial void OnAttendTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SignedTotal
        {
            get
            {
                return _SignedTotal;
            }
            set
            {
                OnSignedTotalChanging(value);
                ReportPropertyChanging("SignedTotal");
                _SignedTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SignedTotal");
                OnSignedTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _SignedTotal;
        partial void OnSignedTotalChanging(Nullable<global::System.Int32> value);
        partial void OnSignedTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SignedAmount
        {
            get
            {
                return _SignedAmount;
            }
            set
            {
                OnSignedAmountChanging(value);
                ReportPropertyChanging("SignedAmount");
                _SignedAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SignedAmount");
                OnSignedAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _SignedAmount;
        partial void OnSignedAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnSignedAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="CountRow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CountRow : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CountRow 对象。
        /// </summary>
        /// <param name="total">Total 属性的初始值。</param>
        public static CountRow CreateCountRow(global::System.Int32 total)
        {
            CountRow countRow = new CountRow();
            countRow.Total = total;
            return countRow;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                if (_Total != value)
                {
                    OnTotalChanging(value);
                    ReportPropertyChanging("Total");
                    _Total = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Total");
                    OnTotalChanged();
                }
            }
        }
        private global::System.Int32 _Total;
        partial void OnTotalChanging(global::System.Int32 value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Signed
        {
            get
            {
                return _Signed;
            }
            set
            {
                OnSignedChanging(value);
                ReportPropertyChanging("Signed");
                _Signed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Signed");
                OnSignedChanged();
            }
        }
        private Nullable<global::System.Int32> _Signed;
        partial void OnSignedChanging(Nullable<global::System.Int32> value);
        partial void OnSignedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quarter
        {
            get
            {
                return _Quarter;
            }
            set
            {
                OnQuarterChanging(value);
                ReportPropertyChanging("Quarter");
                _Quarter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quarter");
                OnQuarterChanged();
            }
        }
        private Nullable<global::System.Int32> _Quarter;
        partial void OnQuarterChanging(Nullable<global::System.Int32> value);
        partial void OnQuarterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuaTotal
        {
            get
            {
                return _QuaTotal;
            }
            set
            {
                OnQuaTotalChanging(value);
                ReportPropertyChanging("QuaTotal");
                _QuaTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuaTotal");
                OnQuaTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _QuaTotal;
        partial void OnQuaTotalChanging(Nullable<global::System.Int32> value);
        partial void OnQuaTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuaSigned
        {
            get
            {
                return _QuaSigned;
            }
            set
            {
                OnQuaSignedChanging(value);
                ReportPropertyChanging("QuaSigned");
                _QuaSigned = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuaSigned");
                OnQuaSignedChanged();
            }
        }
        private Nullable<global::System.Int32> _QuaSigned;
        partial void OnQuaSignedChanging(Nullable<global::System.Int32> value);
        partial void OnQuaSignedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Week
        {
            get
            {
                return _Week;
            }
            set
            {
                OnWeekChanging(value);
                ReportPropertyChanging("Week");
                _Week = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Week");
                OnWeekChanged();
            }
        }
        private Nullable<global::System.Int32> _Week;
        partial void OnWeekChanging(Nullable<global::System.Int32> value);
        partial void OnWeekChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WeekSigned
        {
            get
            {
                return _WeekSigned;
            }
            set
            {
                OnWeekSignedChanging(value);
                ReportPropertyChanging("WeekSigned");
                _WeekSigned = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekSigned");
                OnWeekSignedChanged();
            }
        }
        private Nullable<global::System.Int32> _WeekSigned;
        partial void OnWeekSignedChanging(Nullable<global::System.Int32> value);
        partial void OnWeekSignedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="CustomerRow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerRow : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CustomerRow 对象。
        /// </summary>
        /// <param name="customerID">CustomerID 属性的初始值。</param>
        public static CustomerRow CreateCustomerRow(global::System.Int64 customerID)
        {
            CustomerRow customerRow = new CustomerRow();
            customerRow.CustomerID = customerID;
            return customerRow;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int64 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int64 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="InviteRow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InviteRow : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 InviteRow 对象。
        /// </summary>
        /// <param name="inviteID">InviteID 属性的初始值。</param>
        public static InviteRow CreateInviteRow(global::System.Int64 inviteID)
        {
            InviteRow inviteRow = new InviteRow();
            inviteRow.InviteID = inviteID;
            return inviteRow;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 InviteID
        {
            get
            {
                return _InviteID;
            }
            set
            {
                if (_InviteID != value)
                {
                    OnInviteIDChanging(value);
                    ReportPropertyChanging("InviteID");
                    _InviteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InviteID");
                    OnInviteIDChanged();
                }
            }
        }
        private global::System.Int64 _InviteID;
        partial void OnInviteIDChanging(global::System.Int64 value);
        partial void OnInviteIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Industry
        {
            get
            {
                return _Industry;
            }
            set
            {
                OnIndustryChanging(value);
                ReportPropertyChanging("Industry");
                _Industry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Industry");
                OnIndustryChanged();
            }
        }
        private global::System.String _Industry;
        partial void OnIndustryChanging(global::System.String value);
        partial void OnIndustryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IndustryDes
        {
            get
            {
                return _IndustryDes;
            }
            set
            {
                OnIndustryDesChanging(value);
                ReportPropertyChanging("IndustryDes");
                _IndustryDes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IndustryDes");
                OnIndustryDesChanged();
            }
        }
        private global::System.String _IndustryDes;
        partial void OnIndustryDesChanging(global::System.String value);
        partial void OnIndustryDesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private global::System.String _Area;
        partial void OnAreaChanging(global::System.String value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaDes
        {
            get
            {
                return _AreaDes;
            }
            set
            {
                OnAreaDesChanging(value);
                ReportPropertyChanging("AreaDes");
                _AreaDes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaDes");
                OnAreaDesChanged();
            }
        }
        private global::System.String _AreaDes;
        partial void OnAreaDesChanging(global::System.String value);
        partial void OnAreaDesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private global::System.String _Contact;
        partial void OnContactChanging(global::System.String value);
        partial void OnContactChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Attend
        {
            get
            {
                return _Attend;
            }
            set
            {
                OnAttendChanging(value);
                ReportPropertyChanging("Attend");
                _Attend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attend");
                OnAttendChanged();
            }
        }
        private Nullable<global::System.Boolean> _Attend;
        partial void OnAttendChanging(Nullable<global::System.Boolean> value);
        partial void OnAttendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AttendTime
        {
            get
            {
                return _AttendTime;
            }
            set
            {
                OnAttendTimeChanging(value);
                ReportPropertyChanging("AttendTime");
                _AttendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttendTime");
                OnAttendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AttendTime;
        partial void OnAttendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAttendTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsExternal
        {
            get
            {
                return _IsExternal;
            }
            set
            {
                OnIsExternalChanging(value);
                ReportPropertyChanging("IsExternal");
                _IsExternal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExternal");
                OnIsExternalChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsExternal;
        partial void OnIsExternalChanging(Nullable<global::System.Boolean> value);
        partial void OnIsExternalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ProductAmount
        {
            get
            {
                return _ProductAmount;
            }
            set
            {
                OnProductAmountChanging(value);
                ReportPropertyChanging("ProductAmount");
                _ProductAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductAmount");
                OnProductAmountChanged();
            }
        }
        private Nullable<global::System.Double> _ProductAmount;
        partial void OnProductAmountChanging(Nullable<global::System.Double> value);
        partial void OnProductAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SignedTime
        {
            get
            {
                return _SignedTime;
            }
            set
            {
                OnSignedTimeChanging(value);
                ReportPropertyChanging("SignedTime");
                _SignedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SignedTime");
                OnSignedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _SignedTime;
        partial void OnSignedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSignedTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                OnActivityIDChanging(value);
                ReportPropertyChanging("ActivityID");
                _ActivityID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActivityID");
                OnActivityIDChanged();
            }
        }
        private global::System.String _ActivityID;
        partial void OnActivityIDChanging(global::System.String value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
